server:
  port: 8040

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/project
    username: admin
    password: admin
  sql:
    init:
      mode: always
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    propertues:
      spring.json.type.mapping:
        

application:
  config:
    user-url: http://localhost:8010/api/v1/user
    task-url: http://localhost:8020/api/v1/task
    file-url: http://localhost:8050/api/v1/file