server:
  port: 8010
spring:
  datasource:
    driver-calss-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user
    useername: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect