server:
  port: 8010
spring:
  datasource:
    driver-calss-name: org.postgresql.Driver
    url: jdbc:mysql://localhost:3306/user
    useername: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
      database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect